# -*- coding: utf-8 -*-
"""Atividade ativa - probabilidade e estatistica 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mc7NAbKRRHGi-T-IF8vfFe2kA3ad3zDs

<h1><center>IESB EAD - Probabilidade e estatistica</h1>

# Caro aluno,

Pontuação (0,25 Pontos)
*	Quantas reclamações foram registradas em 2016, contidas nesta base?

  * Reclamações no ano de 2016: 203486

*	Qual região houve mais reclamação? E qual houve menos?
  * Região com menor número de reclamações: Norte
  * Região com maior número de reclamações: Nordeste

*	Qual a quantidade de reclamações realizadas por homens? E por mulheres?

Pontuação (0,25 Pontos)
*	Em qual região os homens fizeram mais reclamações que as mulheres?

  * Região em que homens fizeram mais reclamações que mulheres: Sul

*	Qual a faixa etária que realizou mais reclamações?
  * Faixa etária que realizou mais reclamações: entre 31 a 40 anos

*	Quais assuntos apresentaram mais reclamações em 2016?
  * Assuntos apresentaram mais reclamações em 2016: Telefone ( Convencional, Celular, Interfone, Etc. )

*	Analisando o nome fantasia, determine qual empresa recebeu mais reclamações em 2016.
  * Empresa recebeu mais reclamações em 2016: OI

*	Qual empresa possui um maior percentual de resolução de reclamações?
  * Empresa que possui o maior percentual de resolução de reclamações: MARCOS WENDER RODRIGUES DE MOURA: Percentual: 99.0


Pontuação (1 Ponto)

*	Monte um gráfico mostrando a quantidade de reclamações por região, separando as mesmas por sexo.
  * Anexo Questão 3.1.

*	Elabore um gráfico de linhas com a quantidade de reclamações por mês. Este gráfico lembra alguma distribuição estatística?

*	Elabore um gráfico boxplot mostrando a quantidade de reclamações por região.
  * Anexo Questão 3.3.

Pontuação (0,5 Pontos)

*	É possível afirmar que existe correlação entre o número de reclamações E o número de habitantes por Estado? Elabore um gráfico de dispersão e calcule o índice de correlação destes dois fatores.

  * Não há correlação forte entre o número de reclamações e o número de habitantes por estado.
  Grafico anexo Questão 4.


Todo o trabalho deverá ser feito utilizando notebook Python. Pode ser utilizado a plataforma Google Colaboratory e todos os itens acima deverão ser demonstrados. NÃO SERÃO ACEITO APENAS AS RESPOSTAS AS PERGUNTAS. O aluno deverá apresentar todos os comandos utilizados para obter as informações solicitadas.

O aluno deverá imprimir o notebook em formato PDF e submeter no campo atividade ativa, juntamente com o Notebook do projeto. 

Não serão corrigidos trabalhos com formato diferente de PDF como .ZIP,tar, ou imagens.

#Material de Apoio para uso do Pandas

https://www.kaggle.com/joaoavf/introducao-a-analise-de-dados-python-e-pandas
"""

#Iniciando a utilização da biblioteca pandas
import pandas as pd
import seaborn as sns

#Os dados podem ser importados diretamente da internet, sem a necessidade de ser armazenada no computador local utilizando os comandos listados abaixo
#Fazendo o upload via google Drive. Para isso será necessário o uso de uma função que foi desenvolvida abaixo

import requests
from io import StringIO

RED = '\033[31m'
ENDC = '\033[m'
GREEN = '\033[32m'
YELLOW = '\033[33m'
PINK = '\033[45m'
BLUE = '\033[46m'

orig_url='https://drive.google.com/file/d/1pkOP40FvztNt0pnWgKMG5iTXzRt4TW_N/view?usp=sharing'
file_id = orig_url.split('/')[-2]
dwn_url='https://drive.google.com/uc?export=download&id=' + file_id

url = requests.get(dwn_url).text
csv_raw = StringIO(url)
dfs = pd.read_csv(csv_raw)


def get_borda(direcao, desc_text, key_name):
    i_sorted = dfs.groupby([key_name]).size().sort_values()
    borda = i_sorted.tail(1) if direcao == "teto" else i_sorted.head(1)
    print(f"{YELLOW}{desc_text}:{ENDC} {borda.keys()[0]}")
    print("-----------------------")

def topCampo(desc, key):
    get_borda("teto", desc, key)   

def botCampo(desc, key):
    get_borda("piso", desc, key)

# Questão 1.1: total de reclamações no ano de 2016

total_rec = sum(dfs['ï»¿AnoCalendario'] == 2016)

print(f"{YELLOW}Reclamações no ano de 2016:{ENDC} {total_rec}")
print("-----------------------")

# Questão 1.2: região com maior e menor número de reclamações

botCampo("Região com menor número de reclamações", "Regiao")
topCampo("Região com maior número de reclamações", "Regiao")

# Questão 1.3: Quantidade de reclamações realizadas por homens e mulheres

total_masc = sum(dfs['SexoConsumidor'] == 'M')
total_fem = sum(dfs['SexoConsumidor'] == 'F')

print(f"{YELLOW}Reclamações feitas por homens:{ENDC} {total_masc}")
print(f"{YELLOW}Reclamações feitas por mulheres:{ENDC} {total_fem}")
print("-----------------------")

# Questão 2.1: região em que homens fizeram mais reclamações que mulheres

lst_sex_reg = dfs[['Regiao', 'SexoConsumidor']]

rmhqm = []

for Regiao, SexoConsumidor in lst_sex_reg.groupby(['Regiao']):
    
    ms = (SexoConsumidor['SexoConsumidor']).groupby(SexoConsumidor['SexoConsumidor'] == "M").count()[1]
    fs = (SexoConsumidor['SexoConsumidor']).groupby(SexoConsumidor['SexoConsumidor'] == "F").count()[1]
    
    if ms > fs:
        rmhqm.append({"Regiao": Regiao, "Diff": ms - fs })    

rmhqm.sort(key = lambda d: d["Diff"], reverse = True)

print(f"{YELLOW}Região em que homens fizeram mais reclamações que mulheres: {rmhqm[0]['Regiao']}{ENDC}")
print("-----------------------")

# Questão 2.2: Qual a faixa etária que realizou mais reclamações
topCampo("Faixa etária que realizou mais reclamações", "FaixaEtariaConsumidor")

# Questão 2.3: Quais assuntos apresentaram mais reclamações em 2016
topCampo("Assuntos apresentaram mais reclamações em 2016", "DescricaoAssunto")

# Questão 2.4: Qual empresa recebeu mais reclamações em 2016
topCampo("Empresa recebeu mais reclamações em 2016", "strNomeFantasia")

# Questão 2.5: Qual empresa possui um maior percentual de resolução de reclamações

lista_t = dfs[['strRazaoSocial', 'Atendida']].value_counts(ascending=True)

perc = 0.0
empresa = ''

for razao_social in dfs['strRazaoSocial'].unique():
    qtd_atend = 0
    qtd_natend = 0

    if (razao_social,'S') in lista_t:        
        qtd_atend = lista_t[razao_social,'S']

    if (razao_social,'N') in lista_t:
        qtd_natend = lista_t[razao_social,'N']

    if qtd_atend != 0 and qtd_natend != 0:        
        perc_calc = qtd_atend / qtd_natend
        if perc_calc > perc:
            perc = perc_calc
            empresa = razao_social

print(f"{YELLOW}Empresa possui um maior percentual de resolução de reclamações:{ENDC} {empresa}: Percentual: {perc}")
print("-----------------------")

# Questão 3.1: Monte um gráfico mostrando a quantidade de reclamações por região, separando as mesmas por sexo.
lst_sex_reg = dfs[['Regiao', 'SexoConsumidor']]
graph = sns.countplot(x='Regiao', hue='SexoConsumidor',data=lst_sex_reg)

# Questão 3.2: Elabore um gráfico de linhas com a quantidade de reclamações por mês. Este gráfico lembra alguma distribuição estatística?
dfs['DataAbertura'].value_counts()

# Questão 3.3: Elabore um gráfico boxplot mostrando a quantidade de reclamações por região.
lst_rec_reg = dfs['Regiao'].value_counts().plot.bar()

# Questão 4: É possível afirmar que existe correlação entre o número de reclamações E o número de habitantes por Estado? Elabore um gráfico de dispersão e calcule o índice de correlação destes dois fatores.
lst_join = []
estados = {
'AL': 3120494,
'AM': 3483985,
'BA': 14016906,
'CE': 8452381,
'DF': 2570160,
'ES': 3514952,
'GO': 6003788,
'MA': 6574789,
'MG': 19597330,
'MS': 2449024,
'MT': 3035122,
'PA': 7581051,
'PB': 3766528 ,
'PE': 8796448,
'PI': 3118360,
'PR': 10444526,
'RJ': 15989929,
'RN': 10693929,
'RO': 1562409,
'RS': 10693929,
'SC': 6248436 ,
'SP': 41262199,
'TO': 1383445}



lst_rec_uf = dfs['UF'].value_counts()

lst_estados = []
lst_pop = []
lst_rec = []

for estado in dfs['UF'].unique():
    if estado in estados:
        
        lst_estados.append(estado)        
        lst_pop.append(estados[estado])
        lst_rec.append(lst_rec_uf[estado])         

df = pd.DataFrame({'UF': lst_estados, 'Rec':lst_rec,'Pop':lst_pop}) 
print(df.std())

sns.scatterplot(x='Rec', y='Pop', data=df,hue='UF')


# É possível afirmar que existe correlação entre o número de reclamações E o número de habitantes por Estado?
# não há correlação forte entre o número de reclamações e o número de habitantes por estado.